title: Vinicius Augusto
baseurl: ""
url: "https://vinicius-92.github.io"
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_style: overflow
palette: blue
header:
  title: Vinicius Augusto
  tagline: Junior Java Developer
  profile_img: images/avatar.jpeg
  profile_img_alt: Author avatar
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Blog
      url: /blog/
      style: link
    - label: Contato
      url: /contact/
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/antivinicius'
      style: icon
      icon_class: twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/vinicius_aug'
      style: icon
      icon_class: instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/vinicius-92'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/vinicius-92'
      style: icon
      icon_class: linkedin
      new_window: true

footer:
  content: >-
    
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
